name: master
run-name: Master CI
on:
  push:
    branches: [master]
jobs:
  financial-products-service-tests:
    name: FinancialProductsService tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Run tests
        run: dotnet test PedroTer7.FinancialMonkey.FinancialProductsService.Tests/PedroTer7.FinancialMonkey.FinancialProductsService.Tests.csproj
  publish_authservice_image:
    name: Publish AuthService image
    runs-on: ubuntu-latest
    needs: [financial-products-service-tests]
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and publish to DockerHub
        uses: docker/build-push-action@v5.1.0
        with:
          file: 'AuthService.Dockerfile'
          push: true
          tags: pedroter7/financial-monkey-authservice:latest
  publish_idserver_image:
    name: Publish IdentityServer image
    runs-on: ubuntu-latest
    needs: [financial-products-service-tests]
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and publish to DockerHub
        uses: docker/build-push-action@v5.1.0
        with:
          file: 'IdentityServer.Dockerfile'
          push: true
          tags: pedroter7/financial-monkey-identityserver-migrations:latest
  publish_financialproductsservice_image:
    name: Publish FinancialProductService image
    runs-on: ubuntu-latest
    needs: [financial-products-service-tests]
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and publish to DockerHub
        uses: docker/build-push-action@v5.1.0
        with:
          file: 'FinancialProductsService.Dockerfile'
          push: true
          tags: pedroter7/financial-monkey-financialproductsservice:latest
  
