name: master
run-name: Master CI
on:
  push:
    branches: [master]
jobs:
  financial-products-service-tests:
    name: FinancialProductsService tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Run tests
        run: dotnet test PedroTer7.FinancialMonkey.FinancialProductsService.Tests/PedroTer7.FinancialMonkey.FinancialProductsService.Tests.csproj
